[workspace]
resolver = "2"
members = ["crates/*"]

[lib]
path = "crates/benda/lib.rs"

[package]
name = "Benda"
description = "Use Bend language functions and capabilities in Python!"
license = "MIT"
publish = true
version = "0.1.1"
