name: Benda CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  checks:
    name: Nix and Rust checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Clippy
        run: nix develop -c cargo clippy

      - name: Check Rust formatting
        run: nix develop -c cargo fmt --check

      - name: Check flake.lock
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
